# Generated by Django 5.0.2 on 2025-04-06 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Task1', '0003_course_credits'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
